#!/bin/bash -e
log-helper level eq trace && set -x

# This tool helps to generate tls certificates with cfssl
# or get certificates from a json file

PREFIX=$1
CERT_FILE=$2
KEY_FILE=$3
CA_FILE=$4

log-helper debug "Hi! I'm ssl-helper, what button should i press ?"

# set env vars
PREFIX=${PREFIX^^} # uppercase

PREFIX_SSL_HELPER_TOOL=${PREFIX}_SSL_HELPER_TOOL
SSL_HELPER_TOOL=${!PREFIX_SSL_HELPER_TOOL:-$SSL_HELPER_TOOL}

source ${CONTAINER_SERVICE_DIR}/:ssl-tools/assets/default-env

# call the certificate tool cfssl-helper (default) or jsonssl-helper
$SSL_HELPER_TOOL $PREFIX $CERT_FILE $KEY_FILE $CA_FILE

exit 0
