#!/bin/bash -e

get_ssl_env_var() {
  PREFIX=`echo $1 | sed 's/\./_/g'`
  PREFIX_UPPERCASE=${PREFIX^^}

  COMMON_NAME=$HOSTNAME

  if [ -n "$HOSTNAME" ]; then
	  COMMON_NAME=$HOSTNAME
  fi

  SSL_COUNTRY_VAR=${PREFIX_UPPERCASE}_COUNTRY
  SSL_STATE_VAR=${PREFIX_UPPERCASE}_STATE
  SSL_LOCATION_VAR=${PREFIX_UPPERCASE}_LOCATION
  SSL_ORGANIZATION_VAR=${PREFIX_UPPERCASE}_ORGANIZATION
  SSL_ORGANIZATIONAL_UNIT_VAR=${PREFIX_UPPERCASE}_ORGANIZATIONAL_UNIT
  SSL_COMMON_NAME_VAR=${PREFIX_UPPERCASE}_COMMON_NAME
  SSL_EMAIL_VAR=${PREFIX_UPPERCASE}_EMAIL

  SSL_COUNTRY=${!SSL_COUNTRY_VAR:-}
  SSL_STATE=${!SSL_STATE_VAR:-}
  SSL_LOCATION=${!SSL_LOCATION_VAR:-}
  SSL_ORGANIZATION=${!SSL_ORGANIZATION_VAR:-A1A Car Wash}
  SSL_ORGANIZATIONAL_UNIT=${!SSL_ORGANIZATIONAL_UNIT_VAR:-}
  SSL_COMMON_NAME=${!SSL_COMMON_NAME_VAR:-$COMMON_NAME}
  SSL_EMAIL=${!SSL_EMAIL_VAR:-}

  if [ -n "${SSL_EMAIL}" ]; then
    SSL_EMAIL="/emailAddress=$SSL_EMAIL"
  fi
}
