#!/bin/bash -e

CFSSL_ENV_VAR_PREFIX=$1
CERT_FILE=$2
KEY_FILE=$3
CA_FILE=$4

if [ -z "$CERT_FILE" ] || [ -z "$KEY_FILE" ] || [ -z "$CA_FILE" ]; then
  echo "Usage: cfssl-helper cert_file key_file ca_file"
  exit 1
fi

setCfsslEnvVar $CFSSL_ENV_VAR_PREFIX
source /container/service-available/cfssl/default-env

if [ ! -e "$CERT_FILE" ] && [ ! -e "$KEY_FILE" ]; then

  echo "No certificate file and certificate key provided, generate:"
  echo "$CERT_FILE"
  echo "$KEY_FILE"

  CSR_FILE="/tmp/csr"
  generateCsr
  generateCert

  rm -f $CSR_FILE
  echo "done"

else
  echo "Files $CERT_FILE or $KEY_FILE already exists,"
  echo "do nothing."
fi


if [ ! -e "$CA_FILE" ]; then

  echo "No CA certificate provided"

  if [ -n "$CFSSL_REMOTE_SERVER" ]; then

    echo "Try to get certificate from $CFSSL_REMOTE_SERVER"
    RESULT=$()
    curl -s -d "{\"label\": \"${CFSSL_REMOTE_SERVER_CA_LABEL}\"}" $CFSSL_REMOTE_SERVER/api/v1/cfssl/info sed -e "s/.*certificate\":\"\(-----.*-----\)\".*/\1/g" | sed 's/\\n/\n/g' > $CA_FILE

  elif [ "$CFSSL_CA" = "default-ca" ]; then

    "Link default-ca certificate to $CA_FILE"
    ln -s /container/service-available/cfssl/assets/default-ca/default-ca.pem $CA_FILE

  elif [ -n "$CFSSL_CA_CERT" ]

    "Link custom cfssl CA cert to $CA_FILE"
    ln -s $CFSSL_CA_CERT $CA_FILE

  else
    echo "unable to get a CA certificate"
    exit 1
  fi

  echo "done"

fi


function generateCsr() {

  cp /container/service-available/cfssl/assets/default-ca/config/req-csr.json.tmpl $CSR_FILE

  sed -i "s|{{ CFSSL_CERT_KEY_ALGO }}|${CFSSL_CERT_KEY_ALGO}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_KEY_SIZE }}|${CFSSL_CERT_KEY_SIZE}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_ORGANIZATION }}|${CFSSL_CERT_ORGANIZATION}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_ORGANIZATION_UNIT }}|${CFSSL_CERT_ORGANIZATION_UNIT}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_LOCATION }}|${CFSSL_CERT_LOCATION}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_STATE }}|${CFSSL_CERT_STATE}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_COUNTRY }}|${CFSSL_CERT_COUNTRY}|g" $CSR_FILE
  sed -i "s|{{ CFSSL_CERT_CN }}|${CFSSL_CERT_CN}|g" $CSR_FILE

  # cert_cn is the first hostname
  IFS=',' read -r -a host_array <<< "$CFSSL_CERT_HOSTS"
  for host in "${host_array[@]}"
  do
    sed -i "s|\"{{ CFSSL_CERT_HOSTS }}\"|\"${host}\",\n    \"{{ CFSSL_CERT_HOSTS }}\"|g" $CSR_FILE
    LAST_HOST=$host
  done
  sed -i "s|    \"$LAST_HOST\",|    \"$LAST_HOST\"|g" $CSR_FILE
  sed -i "/{{ CFSSL_CERT_HOSTS }}/d" $CSR_FILE

}


function generateCert() {

  if [ -n "$CFSSL_REMOTE_SERVER" ]; then
    cfssl gencert -remote=$CFSSL_REMOTE_SERVER -label="$CFSSL_REMOTE_SERVER_CA_LABEL" $CSR_FILE | cfssljson -bare /tmp/cert
  else

    if [ "$CFSSL_CA" = "default-ca" ]; then
      CFSSL_CA_CERT="/container/service-available/cfssl/assets/default-ca/default-ca.pe"
      CFSSL_CA_KEY="/container/service-available/cfssl/assets/default-ca/default-ca-key.pem"
      CFSSL_CA_CONFIG="/container/service-available/cfssl/assets/default-ca/config/ca-config.json"
    fi

    CA_CERT_PARAM=""
    CA_KEY_PARAM=""
    CA_CONFIG_PARAM=""

    [[ -n "$CFSSL_CA_CERT" ]] && CA_CERT_PARAM="-ca CFSSL_CA_CERT"
    [[ -n "$CFSSL_CA_KEY" ]] && CA_KEY_PARAM="-ca-key $CFSSL_CA_KEY"
    [[ -n "$CFSSL_CA_CONFIG" ]] && CA_CONFIG_PARAM="-config $CFSSL_CA_CONFIG"

    cfssl gencert $CA_CERT_PARAM $CA_KEY_PARAM $CA_CONFIG_PARAM $CSR_FILE | cfssljson -bare /tmp/cert
  fi

  # move generated files
  mv /tmp/cert.pem $CERT_FILE
  mv /tmp/cert-key.pem $KEY_FILE

  rm -rf /tmp/*.csr /tmp/*.pem

}


function setCfsslEnvVar() {

  PREFIX=$1
  PREFIX=${PREFIX^^}

  if [ -z "$PREFIX" ]; then
    echo "error: getCfsslEnvVar no prefix provided"
    exit 1
  fi

  CFSSL_CA=${PREFIX}_CFSSL_CA
  CFSSL_REMOTE_SERVER=${PREFIX}_CFSSL_REMOTE_SERVER
  CFSSL_REMOTE_SERVER_CA_LABEL=${PREFIX}_CFSSL_REMOTE_SERVER_CA_LABEL

  CFSSL_CERT_CN=${PREFIX}_CFSSL_CERT_CN
  CFSSL_CERT_HOSTS=${PREFIX}_CFSSL_CERT_HOSTS

  CFSSL_CERT_KEY_ALGO=${PREFIX}_CFSSL_CERT_KEY_ALGO
  CFSSL_CERT_KEY_SIZE=${PREFIX}_CFSSL_CERT_KEY_SIZE

  CFSSL_CERT_ORGANIZATION=${PREFIX}_CFSSL_CERT_ORGANIZATION
  CFSSL_CERT_ORGANIZATION_UNIT=${PREFIX}_CFSSL_CERT_ORGANIZATION_UNIT
  CFSSL_CERT_LOCATION=${PREFIX}_CFSSL_CERT_LOCATION
  CFSSL_CERT_STATE=${PREFIX}_CFSSL_CERT_STATE
  CFSSL_CERT_COUNTRY=${PREFIX}_CFSSL_CERT_COUNTRY

  CFSSL_CA_CERT=${PREFIX}_CFSSL_CA_CERT
  CFSSL_CA_KEY=${PREFIX}_CFSSL_CA_KEY
  CFSSL_CA_CONFIG=${PREFIX}_CFSSL_CA_CONFIG

}
