#!/bin/bash -e

# Usage :
# RUN /sbin/add-service-available [service1] [service2] ...

for i in $@
do

  echo "add-service-available: $i"
  if  [ -d "/osixia/service-available/$i" ]; then

    if [ ! -d "/osixia/service/$i" ]; then
      cp -R /osixia/service-available/$i /osixia/service/$i
    else
      echo "Directory /osixia/service/$i already exists, another service has the same name."
      exit 1
    fi
  fi
done
