#!/bin/bash -e

CALL=$1

function iterate() {
  local ENV_VAR_NAME=$1
  local ENV_VAR=${!ENV_VAR_NAME}

  if [ $(complex-bash-env isTable "$ENV_VAR") = true ]; then
    echo $(complex-bash-env stripTablePrefix "$ENV_VAR")
  else
    echo "$ENV_VAR_NAME"
  fi
}

function isTable() {
  local ENV_VAR=$1
  if [ $(echo $ENV_VAR | grep "#COMPLEX_BASH_ENV:TABLE:" -c ) -eq 1 ]; then
    echo true
  else
    echo false
  fi
}

function isRow() {
  local ENV_VAR=$1
  if [ $(echo $ENV_VAR | grep "#COMPLEX_BASH_ENV:ROW:" -c ) -eq 1 ]; then
    echo true
  else
    echo false
  fi
}

function getRowKey() {
  local ENV_VAR=$1
  local ROW_KEY_VAR_NAME=$(complex-bash-env getRowKeyVarName "$ENV_VAR")
  echo "${!ROW_KEY_VAR_NAME}"
}

function getRowValue() {
  local ENV_VAR=$1
  local ROW_VALUE_VAR_NAME=$(complex-bash-env getRowValueVarName "$ENV_VAR")
  echo "${!ROW_VALUE_VAR_NAME}"
}

function getRowKeyVarName() {
  local ENV_VAR=$1
  local ROW=($(complex-bash-env getRow "$ENV_VAR"))
  echo "${ROW[0]}"
}

function getRowValueVarName() {
  local ENV_VAR=$1
  local ROW=($(complex-bash-env getRow "$ENV_VAR"))
  echo "${ROW[1]}"
}

function getRow() {
  local ENV_VAR=$1
  if [ $(complex-bash-env isRow "$ENV_VAR") = true ]; then
    local ENV_VAR=$(complex-bash-env stripRowPrefix "$ENV_VAR")
    echo "${ENV_VAR}"
  else
    echo "$ENV_VAR is not a complex bash env row"
    exit 1
  fi
}

function stripTablePrefix() {
  local ENV_VAR=$1
  stripPrefix "$ENV_VAR" "#COMPLEX_BASH_ENV:TABLE:"
}

function stripRowPrefix() {
  local ENV_VAR=$1
  stripPrefix "$ENV_VAR" "#COMPLEX_BASH_ENV:ROW:"
}

function stripPrefix() {
  local ENV_VAR=$1
  local PREFIX=$2
  local RETURN=${ENV_VAR#$PREFIX}
  echo $RETURN
}

shift
$CALL "$@"
