#!/bin/bash -e
echo "Install the multiple process stack: runit syslog-ng-core logrotate cron"
/container/tool/install-service-available runit syslog-ng-core logrotate cron
touch /container/multiple_process_stack_installed
