#!/bin/bash -e

# Usage :
# RUN /container/tool/install-service-available [service1] [service2] ...

for i in $@
do

  echo "install-service-available: $i"
  if  [ -d "/container/service-available/$i" ]; then

    if [ -f /container/service-available/$i/install.sh ]; then
      echo "Processing file /container/service-available/$i/install.sh"
      /container/service-available/$i/install.sh
    fi

    if [ -f /container/service-available/$i/daemon.sh ]; then
      echo "link /container/service-available/$i/daemon.sh to /etc/service/$i/run"
      mkdir /etc/service/$i
      ln -sf /container/service-available/$i/daemon.sh /etc/service/$i/run
    fi

    if [ -f /container/service-available/$i/container-start.sh ]; then
      echo "link /container/service-available/$i/container-start.sh to /etc/my_init.d/$i"
      ln -sf /container/service-available/$i/container-start.sh /etc/my_init.d/$i
    fi

  else
    echo "service-available: $i not found in /container/service-available/$i"
    exit 1
  fi
done
