#!/usr/bin/python -u
import os, os.path, subprocess

SERVICE_DIR = "/container/service"
nb_process = 0

print("install-service")
# Auto run global install script if available
if os.path.isfile(SERVICE_DIR + os.sep + "install.sh"):
    print("run " + SERVICE_DIR + os.sep + "install.sh")
    subprocess.call([SERVICE_DIR + os.sep + "install.sh"],shell=True)

    print("remove " + SERVICE_DIR + os.sep + "install.sh\n")
    os.remove(SERVICE_DIR + os.sep + "install.sh")


# Process install script of services in /container/service
for service in sorted(os.listdir(SERVICE_DIR)):

    if os.path.isfile(SERVICE_DIR + os.sep + service + os.sep + "install.sh"):
        print("run " + SERVICE_DIR + os.sep + service + os.sep + "install.sh")
        subprocess.call([SERVICE_DIR + os.sep + service + os.sep + "install.sh"],shell=True)

        print("remove " + SERVICE_DIR + os.sep + service + os.sep + "install.sh")
        os.remove(SERVICE_DIR + os.sep + service + os.sep + "install.sh")

    if os.path.isfile(SERVICE_DIR + os.sep + service + os.sep + "process.sh"):
        nb_process += 1


print(str(nb_process) + " process found.")

# Multiple process image
if nb_process > 1:
    if not os.path.exists("/container/multiple_process_stack_added"):
        print("This image has multiple process.")
        subprocess.call(["/container/tool/add-multiple-process-stack"],shell=True)
        print("For better image build process consider adding:")
        print("\"/container/tool/add-multiple-process-stack\" after an apt-get update in your Dockerfile.")
