#!/bin/bash -e

# Auto run global install script if available
if [ -f "/osixia/service/install.sh" ]; then
  echo "Processing file /osixia/service/install.sh"
  ./osixia/service/install.sh
  rm -f /osixia/service/install.sh
fi

for d in $(find /osixia/service -mindepth 1 -maxdepth 1 -type d); do
  echo "Processing directory ${d}"

  service=$(basename $d)
  echo "service: $service"

  if [ -f "${d}/install.sh" ]; then
    echo "run $service install.sh script"
    ${d}/install.sh
    rm -f ${d}/install.sh
  fi

  if [ -f "${d}/container-start.sh" ]; then
    echo "link $service container-start.sh to /etc/my_init.d/$service"
    ln -s ${d}/container-start.sh /etc/my_init.d/$service
  fi

  if [ -f "${d}/daemon.sh" ]; then
    echo "link $service daemon to /etc/service/$service/run"
    mkdir -p /etc/service/$service
    ln -s ${d}/daemon.sh /etc/service/$service/run
  fi

done

nbDirectories=$(find /etc/service -mindepth 1 -maxdepth 1 -type d | wc -l )
echo "Total number of service: $nbDirectories"

if [ "$nbDirectories" -gt 1 ] && [ ! -e "/etc/multiple_process_stack_installed" ]; then
  echo "This image has multiple process."
  /sbin/install-multiple-process-stack
  echo "For better image build consider adding :"
  echo "\"/sbin/install-multiple-process-stack after\" an apt-get update in your dockerfile."
fi
