#!/bin/bash -e

if [ ! -s "/etc/service" ]; then
  echo "File /etc/service don't exist or is empty, please add in this file the command to execute"
  exit 1
fi

CMD=$(cat /etc/service)

echo "Execute my_init --skip-runit $CMD"
my_init --skip-runit $CMD
