#!/bin/bash -e

# Remove a service
for i in $@
do

  echo "remove-service: $i"

  if [ -d /etc/service/$i ]; then
    echo "remove folder /etc/service/$i"
    rm -rf /etc/service/$i
  fi

  if [ -f /etc/my_init.d/$i ]; then
    echo "remove file /etc/my_init.d/$i"
    rm -f /etc/my_init.d/$i
  fi

  if [ -d /container/service/$i ]; then
    echo "remove folder /container/service/$i"
    rm -rf /container/service/$i
  fi

done
