#!/bin/bash -e

# Remove a service
for i in $@
do

  echo "remove-service: $i"

  if [ -d /container/run/service/$i ]; then
    echo "remove folder /container/run/service/$i"
    rm -rf /container/run/service/$i
  fi

  if [ -f /container/run/startup/$i ]; then
    echo "remove file /container/run/startup/$i"
    rm -f /container/run/startup/$i
  fi

  if [ -d /container/service/$i ]; then
    echo "remove folder /container/service/$i"
    rm -rf /container/service/$i
  fi

done
