#!/bin/bash -e
echo "Searching process..."
nbProcess=$(find /container/run/process -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l )
echo "$nbProcess process found"

# Multiple process image
if [ "$nbProcess" -gt 1 ]; then

  echo "Execute /container/tool/my_init"
  exec /container/tool/my_init

# Single process image
elif [ "$nbProcess" -eq 1 ]; then

  SERVICE=$(find /container/run/process -mindepth 1 -maxdepth 1 -type d)

  echo "Execute /container/tool/my_init --skip-runit $SERVICE/run $@"
  exec /container/tool/my_init --skip-runit $SERVICE/run $@

# No process set: run bash
else
  echo "Execute /container/tool/my_init --skip-runit bash"
  exec /container/tool/my_init --skip-runit bash
fi
