name: osixia
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: false
      - name: golangci-lint baseimage
        uses: golangci/golangci-lint-action@v9
      - name: golangci-lint build
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: build

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck baseimage
        uses: golang/govulncheck-action@v1
      - name: govulncheck build
        uses: golang/govulncheck-action@v1
        with:
          work-dir: build

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [lint, shellcheck, govulncheck]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Vendor baseimage go dependencies
        run: go mod vendor
      - name: Vendor build go dependencies
        run: |
          cd build
          go mod vendor
      - name: Run pipeline
        run: |
          cd build
          go run main.go provider github ../Dockerfile --target "nonroot" --tags-suffix "-nonroot" --github-ref "${GITHUB_REF}" --github-token "${{ secrets.GITHUB_TOKEN }}" --changelog ../CHANGELOG.md --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}" ${{ vars.OSX_GITHUB_FLAGS }}
          go run main.go provider github ../Dockerfile --target "base" --export ../bin --github-ref "${GITHUB_REF}" --github-token "${{ secrets.GITHUB_TOKEN }}" --changelog ../CHANGELOG.md --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}" ${{ vars.OSX_GITHUB_FLAGS }}
